--- #YAML:1.0
name:               Geo-Postcode
version:            0.17
abstract:           UK Postcode validation and location
author:
    - william ross <wross@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBD::SQLite:  0
    DBI:          0
    Test::More:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
